Vagrant.configure("2") do |config|

  config.vm.box = "bento/debian-13"
  config.vm.boot_timeout = 600

  config.vm.define "gfontaoS" do |server|
    server.vm.hostname = "gfontaoS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "p2_gfontaoS"
    end
    server.vm.provision "shell", path: "scripts/server.sh"
  end

end
