Vagrant.configure("2") do |config|

	config.vm.box = "bento/debian-12"
	config.vm.boot_timeout = 600
	config.vm.communicator = "ssh"

	config.vm.define "gfontao-S" do |gfontao_S|
		gfontao_S.vm.hostname = "gfontao-S"
		gfontao_S.vm.network "private_network", ip: "192.168.56.110"
		gfontao_S.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
			vb.cpus = 1
			vb.name = "p2_gfontao-S"
		end
		gfontao_S.vm.provision "shell", path: "scripts/server.sh"
	end

end
