Vagrant.configure("2") do |config|

	config.vm.box = "debian/trixie64"

	config.vm.define "goncaloS" do |goncaloS|
		goncaloS.vm.hostname = "GoncaloS"
		goncaloS.vm.network "private_network", ip: "192.168.56.110"
		goncaloS.vm.provider "virtualbox" do |vb|
			vb.memory = "512"
			vb.cpus = 1
		end
		goncaloS.vm.provision "shell", inline: <<-SHELL
			apt-get update
			apt-get install -y curl inotify-tools
			curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -
			inotifywait -e create /var/lib/rancher/k3s/server/ | grep -q node-token
			sudo cp /var/lib/rancher/k3s/server/node-token /vagrant/k3s-token
			cp /usr/local/bin/k3s /usr/local/bin/kubectl
		SHELL
	end

	config.vm.define "goncaloSW" do |goncaloSW|
		goncaloSW.vm.hostname = "GoncaloSW"
		goncaloSW.vm.network "private_network", ip: "192.168.56.111"
		goncaloSW.vm.provider "virtualbox" do |vb|
			vb.memory = "512"
			vb.cpus = 1
		end
		goncaloSW.vm.provision "shell", inline: <<-SHELL
			apt-get update
			apt-get install -y curl inotify-tools
			inotifywait -e create /vagrant/ | grep -q k3s-token
			K3S_TOKEN=$(cat /vagrant/k3s-token)
			K3S_URL="https://192.168.56.110:6443"
			curl -sfL https://get.k3s.io | K3S_URL=$K3S_URL K3S_TOKEN=$K3S_TOKEN sh -
			cp /usr/local/bin/k3s /usr/local/bin/kubectl
		SHELL
	end

end